AMAZON_CONNECT_INSTANCE_ARN: ""
DELIVERY_EMAIL: ""
ADMIN_EMAIL: ""
ADMIN_FIRST_NAME: ""
ADMIN_LAST_NAME: ""
MANAGER_EMAIL: ""
MANAGER_FIRST_NAME: ""
MANAGER_LAST_NAME: ""
AVAILABLE_SMS_COUNTRIES: 'us,ca'
SIGNED_RECORDING_URL_EXP: 900